version: '3.8'
services:
  mysql:
    image: mysql:8.3  # Официальный MySQL 8.3
    container_name: mysql-app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ermakoff
      MYSQL_USER: testsforusers
      MYSQL_PASSWORD: testsforusers
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
